FROM ubuntu:latest

WORKDIR /usr/src 

ENV TZ=Europe/Prague
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && apt install  -y \
    build-essential \
    tzdata \
    cmake \
    libboost-all-dev \
    postgresql \
    libpq-dev \
    libssl-dev \
    libpqxx-dev \
    openssl \
    git

COPY . .

RUN mkdir build && cd build && cmake .. && make 

EXPOSE 18080

CMD ["/usr/src/build/server"]

