FROM ubuntu:latest

WORKDIR /usr/src 

RUN apt update && apt install  -y \
    build-essential \
    cmake \
    git \
    libboost-all-dev \
    git

COPY . .

RUN git clone https://github.com/CrowCpp/Crow 



